// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

  "starter-kit-example": {
    name: "starter-kit-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/starter-kit-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/starter-kit-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "search-and-replace-example": {
    name: "search-and-replace-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/search-and-replace-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/search-and-replace-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "color-highlight-example": {
    name: "color-highlight-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/color-highlight-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/color-highlight-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "image-placeholder-example": {
    name: "image-placeholder-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/image-placeholder-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/image-placeholder-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "image-extended-example": {
    name: "image-extended-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/examples/image-extended-example.tsx"],
    component: React.lazy(() => import("@/registry/examples/image-extended-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "starter-kit": {
    name: "starter-kit",
    description: "",
    type: "registry:block",
    registryDependencies: ["separator","button","tooltip"],
    files: ["src/registry/toolbars/bold.tsx","src/registry/toolbars/blockquote.tsx","src/registry/toolbars/bullet-list.tsx","src/registry/toolbars/code.tsx","src/registry/toolbars/code-block.tsx","src/registry/toolbars/hard-break.tsx","src/registry/toolbars/horizontal-rule.tsx","src/registry/toolbars/italic.tsx","src/registry/toolbars/ordered-list.tsx","src/registry/toolbars/redo.tsx","src/registry/toolbars/strikethrough.tsx"],
    component: React.lazy(() => import("@/registry/toolbars/bold.tsx")),
    source: "src/__registry__/toolbars/bold.tsx",
    category: "",
    subcategory: "",
    chunks: []
  },
  "search-and-replace": {
    name: "search-and-replace",
    description: "",
    type: "registry:block",
    registryDependencies: ["button","input","label","popover","checkbox","tooltip","separator"],
    files: ["src/registry/extensions/search-and-replace.tsx","src/registry/toolbars/search-and-replace-toolbar.tsx"],
    component: React.lazy(() => import("@/registry/extensions/search-and-replace.tsx")),
    source: "src/__registry__/extensions/search-and-replace.tsx",
    category: "",
    subcategory: "",
    chunks: []
  },
  "color-and-highlight": {
    name: "color-and-highlight",
    description: "",
    type: "registry:block",
    registryDependencies: ["popover","tooltip","button","scroll-area","separator"],
    files: ["src/registry/toolbars/color-and-highlight.tsx"],
    component: React.lazy(() => import("@/registry/toolbars/color-and-highlight.tsx")),
    source: "src/__registry__/toolbars/color-and-highlight.tsx",
    category: "",
    subcategory: "",
    chunks: []
  },
  "image-placeholder": {
    name: "image-placeholder",
    description: "",
    type: "registry:block",
    registryDependencies: ["input","popover","button","tabs","dropdown-menu","separator"],
    files: ["src/registry/extensions/image-placeholder.tsx","src/registry/extensions/image.tsx","src/registry/toolbars/image-placeholder-toolbar.tsx"],
    component: React.lazy(() => import("@/registry/extensions/image-placeholder.tsx")),
    source: "src/__registry__/extensions/image-placeholder.tsx",
    category: "",
    subcategory: "",
    chunks: []
  },
  "image": {
    name: "image",
    description: "",
    type: "registry:block",
    registryDependencies: ["input","popover","button","tabs","dropdown-menu","separator"],
    files: ["src/registry/extensions/image-placeholder.tsx","src/registry/extensions/image.tsx","src/registry/toolbars/image-placeholder-toolbar.tsx"],
    component: React.lazy(() => import("@/registry/extensions/image-placeholder.tsx")),
    source: "src/__registry__/extensions/image-placeholder.tsx",
    category: "",
    subcategory: "",
    chunks: []
  },
  "toolbar-provider": {
    name: "toolbar-provider",
    description: "",
    type: "registry:block",
    registryDependencies: undefined,
    files: ["src/registry/toolbars/toolbar-provider.tsx"],
    component: React.lazy(() => import("@/registry/toolbars/toolbar-provider.tsx")),
    source: "src/__registry__/toolbars/toolbar-provider.tsx",
    category: "",
    subcategory: "",
    chunks: []
  },
  "starter-kit-toolbar-example": {
    name: "starter-kit-toolbar-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/toolbar-examples/starter-kit-toolbar-example.tsx"],
    component: React.lazy(() => import("@/registry/toolbar-examples/starter-kit-toolbar-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "search-and-replace-toolbar-example": {
    name: "search-and-replace-toolbar-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/toolbar-examples/search-and-replace-toolbar-example.tsx"],
    component: React.lazy(() => import("@/registry/toolbar-examples/search-and-replace-toolbar-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "image-placeholder-toolbar-example": {
    name: "image-placeholder-toolbar-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/toolbar-examples/image-placeholder-toolbar-example.tsx"],
    component: React.lazy(() => import("@/registry/toolbar-examples/image-placeholder-toolbar-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
  "color-and-highlight-toolbar-example": {
    name: "color-and-highlight-toolbar-example",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: ["src/registry/toolbar-examples/color-and-highlight-toolbar-example.tsx"],
    component: React.lazy(() => import("@/registry/toolbar-examples/color-and-highlight-toolbar-example.tsx")),
    source: "",
    category: "",
    subcategory: "",
    chunks: []
  },
}
